"""
   /*
   **   Generated by blitz/templates/resouces/combined.vm
   **
   **   Copyright 2007, 2008 Glencoe Software, Inc. All rights reserved.
   **   Use is subject to license terms supplied in LICENSE.txt
   **
   */
"""
import Ice
import IceImport
import omero
IceImport.load("omero_model_DetailsI")
IceImport.load("omero_model_Pixels_ice")
from omero.rtypes import rlong
_omero = Ice.openModule("omero")
_omero_model = Ice.openModule("omero.model")
__name__ = "omero.model"
class PixelsI(_omero_model.Pixels):

      IMAGE =  "ome.model.core.Pixels_image"
      RELATEDTO =  "ome.model.core.Pixels_relatedTo"
      PIXELSTYPE =  "ome.model.core.Pixels_pixelsType"
      SIGNIFICANTBITS =  "ome.model.core.Pixels_significantBits"
      SIZEX =  "ome.model.core.Pixels_sizeX"
      SIZEY =  "ome.model.core.Pixels_sizeY"
      SIZEZ =  "ome.model.core.Pixels_sizeZ"
      SIZEC =  "ome.model.core.Pixels_sizeC"
      SIZET =  "ome.model.core.Pixels_sizeT"
      SHA1 =  "ome.model.core.Pixels_sha1"
      DIMENSIONORDER =  "ome.model.core.Pixels_dimensionOrder"
      PHYSICALSIZEX =  "ome.model.core.Pixels_physicalSizeX"
      PHYSICALSIZEY =  "ome.model.core.Pixels_physicalSizeY"
      PHYSICALSIZEZ =  "ome.model.core.Pixels_physicalSizeZ"
      WAVESTART =  "ome.model.core.Pixels_waveStart"
      WAVEINCREMENT =  "ome.model.core.Pixels_waveIncrement"
      TIMEINCREMENT =  "ome.model.core.Pixels_timeIncrement"
      METHODOLOGY =  "ome.model.core.Pixels_methodology"
      PLANEINFO =  "ome.model.core.Pixels_planeInfo"
      PIXELSFILEMAPS =  "ome.model.core.Pixels_pixelsFileMaps"
      CHANNELS =  "ome.model.core.Pixels_channels"
      SETTINGS =  "ome.model.core.Pixels_settings"
      THUMBNAILS =  "ome.model.core.Pixels_thumbnails"
      ANNOTATIONLINKS =  "ome.model.core.Pixels_annotationLinks"
      DETAILS =  "ome.model.core.Pixels_details"
      def errorIfUnloaded(self):
          if not self._loaded:
              raise _omero.UnloadedEntityException("Object unloaded:"+str(self))

      def throwNullCollectionException(self,propertyName):
          raise _omero.UnloadedEntityException(""+
          "Error updating collection:" + propertyName +"\n"+
          "Collection is currently null. This can be seen\n" +
          "by testing \""+ propertyName +"Loaded\". This implies\n"+
          "that this collection was unloaded. Please refresh this object\n"+
          "in order to update this collection.\n")

      def _toggleCollectionsLoaded(self,load):
          if load:
              self._planeInfoSeq = []
              self._planeInfoLoaded = True;
          else:
              self._planeInfoSeq = []
              self._planeInfoLoaded = False;

          if load:
              self._pixelsFileMapsSeq = []
              self._pixelsFileMapsLoaded = True;
          else:
              self._pixelsFileMapsSeq = []
              self._pixelsFileMapsLoaded = False;

          if load:
              self._channelsSeq = []
              self._channelsLoaded = True;
          else:
              self._channelsSeq = []
              self._channelsLoaded = False;

          if load:
              self._settingsSeq = []
              self._settingsLoaded = True;
          else:
              self._settingsSeq = []
              self._settingsLoaded = False;

          if load:
              self._thumbnailsSeq = []
              self._thumbnailsLoaded = True;
          else:
              self._thumbnailsSeq = []
              self._thumbnailsLoaded = False;

          if load:
              self._annotationLinksSeq = []
              self._annotationLinksLoaded = True;
          else:
              self._annotationLinksSeq = []
              self._annotationLinksLoaded = False;

          pass

      def __init__(self, id = None, loaded = True):
          super(PixelsI, self).__init__()
          # Relying on omero.rtypes.rlong's error-handling
          self._id = rlong(id)
          self._loaded = loaded
          if self._loaded:
             self._details = _omero_model.DetailsI()
             self._toggleCollectionsLoaded(True)

      def unload(self, current = None):
          self._loaded = False
          self.unloadImage( )
          self.unloadRelatedTo( )
          self.unloadPixelsType( )
          self.unloadSignificantBits( )
          self.unloadSizeX( )
          self.unloadSizeY( )
          self.unloadSizeZ( )
          self.unloadSizeC( )
          self.unloadSizeT( )
          self.unloadSha1( )
          self.unloadDimensionOrder( )
          self.unloadPhysicalSizeX( )
          self.unloadPhysicalSizeY( )
          self.unloadPhysicalSizeZ( )
          self.unloadWaveStart( )
          self.unloadWaveIncrement( )
          self.unloadTimeIncrement( )
          self.unloadMethodology( )
          self.unloadPlaneInfo( )
          self.unloadPixelsFileMaps( )
          self.unloadChannels( )
          self.unloadSettings( )
          self.unloadThumbnails( )
          self.unloadAnnotationLinks( )
          self.unloadDetails( )

      def isLoaded(self, current = None):
          return self._loaded
      def unloadCollections(self, current = None):
          self._toggleCollectionsLoaded( False )
      def isGlobal(self, current = None):
          return  False ;
      def isMutable(self, current = None):
          return  True ;
      def isAnnotated(self, current = None):
          return  True ;
      def isLink(self, current = None):
          return  False ;
      def shallowCopy(self, current = None):
            if not self._loaded: return self.proxy()
            copy = PixelsI()
            copy._id = self._id;
            copy._version = self._version;
            copy._details = None  # Unloading for the moment.
            raise omero.ClientError("NYI")
      def proxy(self, current = None):
          if self._id is None: raise omero.ClientError("Proxies require an id")
          return PixelsI( self._id.getValue(), False )

      def getDetails(self, current = None):
          self.errorIfUnloaded()
          return self._details

      def unloadDetails(self, current = None):
          self._details = None

      def getId(self, current = None):
          return self._id

      def setId(self, _id, current = None):
          self._id = _id

      def checkUnloadedProperty(self, value, loadedField):
          if value == None:
              self.__dict__[loadedField] = False
          else:
              self.__dict__[loadedField] = True

      def getVersion(self, current = None):
          self.errorIfUnloaded()
          return self._version

      def setVersion(self, version, current = None):
          self.errorIfUnloaded()
          self._version = version

      def unloadImage(self, ):
          self._imageLoaded = False
          self._image = None;

      def getImage(self, current = None):
          self.errorIfUnloaded()
          return self._image

      def setImage(self, _image, current = None):
          self.errorIfUnloaded()
          self._image = _image
          pass

      def unloadRelatedTo(self, ):
          self._relatedToLoaded = False
          self._relatedTo = None;

      def getRelatedTo(self, current = None):
          self.errorIfUnloaded()
          return self._relatedTo

      def setRelatedTo(self, _relatedTo, current = None):
          self.errorIfUnloaded()
          self._relatedTo = _relatedTo
          pass

      def unloadPixelsType(self, ):
          self._pixelsTypeLoaded = False
          self._pixelsType = None;

      def getPixelsType(self, current = None):
          self.errorIfUnloaded()
          return self._pixelsType

      def setPixelsType(self, _pixelsType, current = None):
          self.errorIfUnloaded()
          self._pixelsType = _pixelsType
          pass

      def unloadSignificantBits(self, ):
          self._significantBitsLoaded = False
          self._significantBits = None;

      def getSignificantBits(self, current = None):
          self.errorIfUnloaded()
          return self._significantBits

      def setSignificantBits(self, _significantBits, current = None):
          self.errorIfUnloaded()
          self._significantBits = _significantBits
          pass

      def unloadSizeX(self, ):
          self._sizeXLoaded = False
          self._sizeX = None;

      def getSizeX(self, current = None):
          self.errorIfUnloaded()
          return self._sizeX

      def setSizeX(self, _sizeX, current = None):
          self.errorIfUnloaded()
          self._sizeX = _sizeX
          pass

      def unloadSizeY(self, ):
          self._sizeYLoaded = False
          self._sizeY = None;

      def getSizeY(self, current = None):
          self.errorIfUnloaded()
          return self._sizeY

      def setSizeY(self, _sizeY, current = None):
          self.errorIfUnloaded()
          self._sizeY = _sizeY
          pass

      def unloadSizeZ(self, ):
          self._sizeZLoaded = False
          self._sizeZ = None;

      def getSizeZ(self, current = None):
          self.errorIfUnloaded()
          return self._sizeZ

      def setSizeZ(self, _sizeZ, current = None):
          self.errorIfUnloaded()
          self._sizeZ = _sizeZ
          pass

      def unloadSizeC(self, ):
          self._sizeCLoaded = False
          self._sizeC = None;

      def getSizeC(self, current = None):
          self.errorIfUnloaded()
          return self._sizeC

      def setSizeC(self, _sizeC, current = None):
          self.errorIfUnloaded()
          self._sizeC = _sizeC
          pass

      def unloadSizeT(self, ):
          self._sizeTLoaded = False
          self._sizeT = None;

      def getSizeT(self, current = None):
          self.errorIfUnloaded()
          return self._sizeT

      def setSizeT(self, _sizeT, current = None):
          self.errorIfUnloaded()
          self._sizeT = _sizeT
          pass

      def unloadSha1(self, ):
          self._sha1Loaded = False
          self._sha1 = None;

      def getSha1(self, current = None):
          self.errorIfUnloaded()
          return self._sha1

      def setSha1(self, _sha1, current = None):
          self.errorIfUnloaded()
          self._sha1 = _sha1
          pass

      def unloadDimensionOrder(self, ):
          self._dimensionOrderLoaded = False
          self._dimensionOrder = None;

      def getDimensionOrder(self, current = None):
          self.errorIfUnloaded()
          return self._dimensionOrder

      def setDimensionOrder(self, _dimensionOrder, current = None):
          self.errorIfUnloaded()
          self._dimensionOrder = _dimensionOrder
          pass

      def unloadPhysicalSizeX(self, ):
          self._physicalSizeXLoaded = False
          self._physicalSizeX = None;

      def getPhysicalSizeX(self, current = None):
          self.errorIfUnloaded()
          return self._physicalSizeX

      def setPhysicalSizeX(self, _physicalSizeX, current = None):
          self.errorIfUnloaded()
          self._physicalSizeX = _physicalSizeX
          pass

      def unloadPhysicalSizeY(self, ):
          self._physicalSizeYLoaded = False
          self._physicalSizeY = None;

      def getPhysicalSizeY(self, current = None):
          self.errorIfUnloaded()
          return self._physicalSizeY

      def setPhysicalSizeY(self, _physicalSizeY, current = None):
          self.errorIfUnloaded()
          self._physicalSizeY = _physicalSizeY
          pass

      def unloadPhysicalSizeZ(self, ):
          self._physicalSizeZLoaded = False
          self._physicalSizeZ = None;

      def getPhysicalSizeZ(self, current = None):
          self.errorIfUnloaded()
          return self._physicalSizeZ

      def setPhysicalSizeZ(self, _physicalSizeZ, current = None):
          self.errorIfUnloaded()
          self._physicalSizeZ = _physicalSizeZ
          pass

      def unloadWaveStart(self, ):
          self._waveStartLoaded = False
          self._waveStart = None;

      def getWaveStart(self, current = None):
          self.errorIfUnloaded()
          return self._waveStart

      def setWaveStart(self, _waveStart, current = None):
          self.errorIfUnloaded()
          self._waveStart = _waveStart
          pass

      def unloadWaveIncrement(self, ):
          self._waveIncrementLoaded = False
          self._waveIncrement = None;

      def getWaveIncrement(self, current = None):
          self.errorIfUnloaded()
          return self._waveIncrement

      def setWaveIncrement(self, _waveIncrement, current = None):
          self.errorIfUnloaded()
          self._waveIncrement = _waveIncrement
          pass

      def unloadTimeIncrement(self, ):
          self._timeIncrementLoaded = False
          self._timeIncrement = None;

      def getTimeIncrement(self, current = None):
          self.errorIfUnloaded()
          return self._timeIncrement

      def setTimeIncrement(self, _timeIncrement, current = None):
          self.errorIfUnloaded()
          self._timeIncrement = _timeIncrement
          pass

      def unloadMethodology(self, ):
          self._methodologyLoaded = False
          self._methodology = None;

      def getMethodology(self, current = None):
          self.errorIfUnloaded()
          return self._methodology

      def setMethodology(self, _methodology, current = None):
          self.errorIfUnloaded()
          self._methodology = _methodology
          pass

      def unloadPlaneInfo(self, current = None):
          self._planeInfoLoaded = False
          self._planeInfoSeq = None;

      def _getPlaneInfo(self, current = None):
          self.errorIfUnloaded()
          return self._planeInfoSeq

      def _setPlaneInfo(self, _planeInfo, current = None):
          self.errorIfUnloaded()
          self._planeInfoSeq = _planeInfo
          self.checkUnloadedProperty(_planeInfo,'planeInfoLoaded')

      def isPlaneInfoLoaded(self):
          return self._planeInfoLoaded

      def sizeOfPlaneInfo(self, current = None):
          self.errorIfUnloaded()
          if not self._planeInfoLoaded: return -1
          return len(self._planeInfoSeq)

      def copyPlaneInfo(self, current = None):
          self.errorIfUnloaded()
          if not self._planeInfoLoaded: self.throwNullCollectionException("planeInfoSeq")
          return list(self._planeInfoSeq)

      def iteratePlaneInfo(self):
          self.errorIfUnloaded()
          if not self._planeInfoLoaded: self.throwNullCollectionException("planeInfoSeq")
          return iter(self._planeInfoSeq)

      def addPlaneInfo(self, target, current = None):
          self.errorIfUnloaded()
          if not self._planeInfoLoaded: self.throwNullCollectionException("planeInfoSeq")
          self._planeInfoSeq.append( target );
          target.setPixels( self )

      def addAllPlaneInfoSet(self, targets, current = None):
          self.errorIfUnloaded()
          if  not self._planeInfoLoaded: self.throwNullCollectionException("planeInfoSeq")
          self._planeInfoSeq.extend( targets )
          for target in targets:
              target.setPixels( self )

      def removePlaneInfo(self, target, current = None):
          self.errorIfUnloaded()
          if not self._planeInfoLoaded: self.throwNullCollectionException("planeInfoSeq")
          self._planeInfoSeq.remove( target )
          target.setPixels( None )

      def removeAllPlaneInfoSet(self, targets, current = None):
          self.errorIfUnloaded()
          if not self._planeInfoLoaded: self.throwNullCollectionException("planeInfoSeq")
          for elt in targets:
              elt.setPixels( None )
              self._planeInfoSeq.remove( elt )

      def clearPlaneInfo(self, current = None):
          self.errorIfUnloaded()
          if not self._planeInfoLoaded: self.throwNullCollectionException("planeInfoSeq")
          for elt in self._planeInfoSeq:
              elt.setPixels( None )
          self._planeInfoSeq = list()

      def reloadPlaneInfo(self, toCopy, current = None):
          self.errorIfUnloaded()
          if self._planeInfoLoaded:
              raise omero.ClientError("Cannot reload active collection: planeInfoSeq")
          if not toCopy:
              raise omero.ClientError("Argument cannot be null")
          if toCopy.getId().getValue() != self.getId().getValue():
             raise omero.ClientError("Argument must have the same id as this instance")
          if toCopy.getDetails().getUpdateEvent().getId().getValue() < self.getDetails().getUpdateEvent().getId().getValue():
             raise omero.ClientError("Argument may not be older than this instance")
          copy = toCopy.copyPlaneInfo() # May also throw
          for elt in copy:
              elt.setPixels( self )
          self._planeInfoSeq = copy
          toCopy.unloadPlaneInfo()
          self._planeInfoLoaded = True

      def unloadPixelsFileMaps(self, current = None):
          self._pixelsFileMapsLoaded = False
          self._pixelsFileMapsSeq = None;

      def _getPixelsFileMaps(self, current = None):
          self.errorIfUnloaded()
          return self._pixelsFileMapsSeq

      def _setPixelsFileMaps(self, _pixelsFileMaps, current = None):
          self.errorIfUnloaded()
          self._pixelsFileMapsSeq = _pixelsFileMaps
          self.checkUnloadedProperty(_pixelsFileMaps,'pixelsFileMapsLoaded')

      def isPixelsFileMapsLoaded(self):
          return self._pixelsFileMapsLoaded

      def sizeOfPixelsFileMaps(self, current = None):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: return -1
          return len(self._pixelsFileMapsSeq)

      def copyPixelsFileMaps(self, current = None):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          return list(self._pixelsFileMapsSeq)

      def iteratePixelsFileMaps(self):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          return iter(self._pixelsFileMapsSeq)

      def addPixelsOriginalFileMap(self, target, current = None):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          self._pixelsFileMapsSeq.append( target );
          target.setChild( self )

      def addAllPixelsOriginalFileMapSet(self, targets, current = None):
          self.errorIfUnloaded()
          if  not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          self._pixelsFileMapsSeq.extend( targets )
          for target in targets:
              target.setChild( self )

      def removePixelsOriginalFileMap(self, target, current = None):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          self._pixelsFileMapsSeq.remove( target )
          target.setChild( None )

      def removeAllPixelsOriginalFileMapSet(self, targets, current = None):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          for elt in targets:
              elt.setChild( None )
              self._pixelsFileMapsSeq.remove( elt )

      def clearPixelsFileMaps(self, current = None):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          for elt in self._pixelsFileMapsSeq:
              elt.setChild( None )
          self._pixelsFileMapsSeq = list()

      def reloadPixelsFileMaps(self, toCopy, current = None):
          self.errorIfUnloaded()
          if self._pixelsFileMapsLoaded:
              raise omero.ClientError("Cannot reload active collection: pixelsFileMapsSeq")
          if not toCopy:
              raise omero.ClientError("Argument cannot be null")
          if toCopy.getId().getValue() != self.getId().getValue():
             raise omero.ClientError("Argument must have the same id as this instance")
          if toCopy.getDetails().getUpdateEvent().getId().getValue() < self.getDetails().getUpdateEvent().getId().getValue():
             raise omero.ClientError("Argument may not be older than this instance")
          copy = toCopy.copyPixelsFileMaps() # May also throw
          for elt in copy:
              elt.setChild( self )
          self._pixelsFileMapsSeq = copy
          toCopy.unloadPixelsFileMaps()
          self._pixelsFileMapsLoaded = True

      def getPixelsFileMapsCountPerOwner(self, current = None):
          return self._pixelsFileMapsCountPerOwner

      def linkOriginalFile(self, addition, current = None):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          link = _omero_model.PixelsOriginalFileMapI()
          link.link( addition, self );
          self.addPixelsOriginalFileMapToBoth( link, True )
          return link

      def addPixelsOriginalFileMapToBoth(self, link, bothSides):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          self._pixelsFileMapsSeq.append( link )
          if bothSides and link.getParent().isLoaded():
              link.getParent().addPixelsOriginalFileMapToBoth( link, False )

      def findPixelsOriginalFileMap(self, removal, current = None):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          result = list()
          for link in self._pixelsFileMapsSeq:
              if link.getParent() == removal: result.append(link)
          return result

      def unlinkOriginalFile(self, removal, current = None):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          toRemove = self.findPixelsOriginalFileMap(removal)
          for next in toRemove:
              self.removePixelsOriginalFileMapFromBoth( next, True )

      def removePixelsOriginalFileMapFromBoth(self, link, bothSides, current = None):
          self.errorIfUnloaded()
          if not self._pixelsFileMapsLoaded: self.throwNullCollectionException("pixelsFileMapsSeq")
          self._pixelsFileMapsSeq.remove( link )
          if bothSides and link.getParent().isLoaded():
              link.getParent().removePixelsOriginalFileMapFromBoth(link, False)

      def linkedOriginalFileList(self, current = None):
          self.errorIfUnloaded()
          if not self.pixelsFileMapsLoaded: self.throwNullCollectionException("PixelsFileMaps")
          linked = []
          for link in self._pixelsFileMapsSeq:
              linked.append( link.getParent() )
          return linked

      def unloadChannels(self, current = None):
          self._channelsLoaded = False
          self._channelsSeq = None;

      def _getChannels(self, current = None):
          self.errorIfUnloaded()
          return self._channelsSeq

      def _setChannels(self, _channels, current = None):
          self.errorIfUnloaded()
          self._channelsSeq = _channels
          self.checkUnloadedProperty(_channels,'channelsLoaded')

      def isChannelsLoaded(self):
          return self._channelsLoaded

      def sizeOfChannels(self, current = None):
          self.errorIfUnloaded()
          if not self._channelsLoaded: return -1
          return len(self._channelsSeq)

      def copyChannels(self, current = None):
          self.errorIfUnloaded()
          if not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          return list(self._channelsSeq)

      def iterateChannels(self):
          self.errorIfUnloaded()
          if not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          return iter(self._channelsSeq)

      def addChannel(self, target, current = None):
          self.errorIfUnloaded()
          if not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          self._channelsSeq.append( target );
          target.setPixels( self )

      def addAllChannelSet(self, targets, current = None):
          self.errorIfUnloaded()
          if  not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          self._channelsSeq.extend( targets )
          for target in targets:
              target.setPixels( self )

      def removeChannel(self, target, current = None):
          self.errorIfUnloaded()
          if not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          self._channelsSeq.remove( target )
          target.setPixels( None )

      def removeAllChannelSet(self, targets, current = None):
          self.errorIfUnloaded()
          if not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          for elt in targets:
              elt.setPixels( None )
              self._channelsSeq.remove( elt )

      def clearChannels(self, current = None):
          self.errorIfUnloaded()
          if not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          for elt in self._channelsSeq:
              elt.setPixels( None )
          self._channelsSeq = list()

      def reloadChannels(self, toCopy, current = None):
          self.errorIfUnloaded()
          if self._channelsLoaded:
              raise omero.ClientError("Cannot reload active collection: channelsSeq")
          if not toCopy:
              raise omero.ClientError("Argument cannot be null")
          if toCopy.getId().getValue() != self.getId().getValue():
             raise omero.ClientError("Argument must have the same id as this instance")
          if toCopy.getDetails().getUpdateEvent().getId().getValue() < self.getDetails().getUpdateEvent().getId().getValue():
             raise omero.ClientError("Argument may not be older than this instance")
          copy = toCopy.copyChannels() # May also throw
          for elt in copy:
              elt.setPixels( self )
          self._channelsSeq = copy
          toCopy.unloadChannels()
          self._channelsLoaded = True

      def getChannel(self, index, current = None):
          self.errorIfUnloaded()
          if not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          return self._channelsSeq[index]

      def setChannel(self, index, element, current = None):
          self.errorIfUnloaded()
          if not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          old = self._channelsSeq[index]
          self._channelsSeq[index] =  element
          if element is not None and element.isLoaded():
              element.setPixels( self )
          return old

      def getPrimaryChannel(self, current = None):
          self.errorIfUnloaded()
          if not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          return self._channelsSeq[0]

      def setPrimaryChannel(self, element, current = None):
          self.errorIfUnloaded()
          if not self._channelsLoaded: self.throwNullCollectionException("channelsSeq")
          index = self._channelsSeq.index(element)
          old = self._channelsSeq[0]
          self._channelsSeq[index] = old
          self._channelsSeq[0] = element
          return old

      def unloadSettings(self, current = None):
          self._settingsLoaded = False
          self._settingsSeq = None;

      def _getSettings(self, current = None):
          self.errorIfUnloaded()
          return self._settingsSeq

      def _setSettings(self, _settings, current = None):
          self.errorIfUnloaded()
          self._settingsSeq = _settings
          self.checkUnloadedProperty(_settings,'settingsLoaded')

      def isSettingsLoaded(self):
          return self._settingsLoaded

      def sizeOfSettings(self, current = None):
          self.errorIfUnloaded()
          if not self._settingsLoaded: return -1
          return len(self._settingsSeq)

      def copySettings(self, current = None):
          self.errorIfUnloaded()
          if not self._settingsLoaded: self.throwNullCollectionException("settingsSeq")
          return list(self._settingsSeq)

      def iterateSettings(self):
          self.errorIfUnloaded()
          if not self._settingsLoaded: self.throwNullCollectionException("settingsSeq")
          return iter(self._settingsSeq)

      def addRenderingDef(self, target, current = None):
          self.errorIfUnloaded()
          if not self._settingsLoaded: self.throwNullCollectionException("settingsSeq")
          self._settingsSeq.append( target );
          target.setPixels( self )

      def addAllRenderingDefSet(self, targets, current = None):
          self.errorIfUnloaded()
          if  not self._settingsLoaded: self.throwNullCollectionException("settingsSeq")
          self._settingsSeq.extend( targets )
          for target in targets:
              target.setPixels( self )

      def removeRenderingDef(self, target, current = None):
          self.errorIfUnloaded()
          if not self._settingsLoaded: self.throwNullCollectionException("settingsSeq")
          self._settingsSeq.remove( target )
          target.setPixels( None )

      def removeAllRenderingDefSet(self, targets, current = None):
          self.errorIfUnloaded()
          if not self._settingsLoaded: self.throwNullCollectionException("settingsSeq")
          for elt in targets:
              elt.setPixels( None )
              self._settingsSeq.remove( elt )

      def clearSettings(self, current = None):
          self.errorIfUnloaded()
          if not self._settingsLoaded: self.throwNullCollectionException("settingsSeq")
          for elt in self._settingsSeq:
              elt.setPixels( None )
          self._settingsSeq = list()

      def reloadSettings(self, toCopy, current = None):
          self.errorIfUnloaded()
          if self._settingsLoaded:
              raise omero.ClientError("Cannot reload active collection: settingsSeq")
          if not toCopy:
              raise omero.ClientError("Argument cannot be null")
          if toCopy.getId().getValue() != self.getId().getValue():
             raise omero.ClientError("Argument must have the same id as this instance")
          if toCopy.getDetails().getUpdateEvent().getId().getValue() < self.getDetails().getUpdateEvent().getId().getValue():
             raise omero.ClientError("Argument may not be older than this instance")
          copy = toCopy.copySettings() # May also throw
          for elt in copy:
              elt.setPixels( self )
          self._settingsSeq = copy
          toCopy.unloadSettings()
          self._settingsLoaded = True

      def unloadThumbnails(self, current = None):
          self._thumbnailsLoaded = False
          self._thumbnailsSeq = None;

      def _getThumbnails(self, current = None):
          self.errorIfUnloaded()
          return self._thumbnailsSeq

      def _setThumbnails(self, _thumbnails, current = None):
          self.errorIfUnloaded()
          self._thumbnailsSeq = _thumbnails
          self.checkUnloadedProperty(_thumbnails,'thumbnailsLoaded')

      def isThumbnailsLoaded(self):
          return self._thumbnailsLoaded

      def sizeOfThumbnails(self, current = None):
          self.errorIfUnloaded()
          if not self._thumbnailsLoaded: return -1
          return len(self._thumbnailsSeq)

      def copyThumbnails(self, current = None):
          self.errorIfUnloaded()
          if not self._thumbnailsLoaded: self.throwNullCollectionException("thumbnailsSeq")
          return list(self._thumbnailsSeq)

      def iterateThumbnails(self):
          self.errorIfUnloaded()
          if not self._thumbnailsLoaded: self.throwNullCollectionException("thumbnailsSeq")
          return iter(self._thumbnailsSeq)

      def addThumbnail(self, target, current = None):
          self.errorIfUnloaded()
          if not self._thumbnailsLoaded: self.throwNullCollectionException("thumbnailsSeq")
          self._thumbnailsSeq.append( target );
          target.setPixels( self )

      def addAllThumbnailSet(self, targets, current = None):
          self.errorIfUnloaded()
          if  not self._thumbnailsLoaded: self.throwNullCollectionException("thumbnailsSeq")
          self._thumbnailsSeq.extend( targets )
          for target in targets:
              target.setPixels( self )

      def removeThumbnail(self, target, current = None):
          self.errorIfUnloaded()
          if not self._thumbnailsLoaded: self.throwNullCollectionException("thumbnailsSeq")
          self._thumbnailsSeq.remove( target )
          target.setPixels( None )

      def removeAllThumbnailSet(self, targets, current = None):
          self.errorIfUnloaded()
          if not self._thumbnailsLoaded: self.throwNullCollectionException("thumbnailsSeq")
          for elt in targets:
              elt.setPixels( None )
              self._thumbnailsSeq.remove( elt )

      def clearThumbnails(self, current = None):
          self.errorIfUnloaded()
          if not self._thumbnailsLoaded: self.throwNullCollectionException("thumbnailsSeq")
          for elt in self._thumbnailsSeq:
              elt.setPixels( None )
          self._thumbnailsSeq = list()

      def reloadThumbnails(self, toCopy, current = None):
          self.errorIfUnloaded()
          if self._thumbnailsLoaded:
              raise omero.ClientError("Cannot reload active collection: thumbnailsSeq")
          if not toCopy:
              raise omero.ClientError("Argument cannot be null")
          if toCopy.getId().getValue() != self.getId().getValue():
             raise omero.ClientError("Argument must have the same id as this instance")
          if toCopy.getDetails().getUpdateEvent().getId().getValue() < self.getDetails().getUpdateEvent().getId().getValue():
             raise omero.ClientError("Argument may not be older than this instance")
          copy = toCopy.copyThumbnails() # May also throw
          for elt in copy:
              elt.setPixels( self )
          self._thumbnailsSeq = copy
          toCopy.unloadThumbnails()
          self._thumbnailsLoaded = True

      def unloadAnnotationLinks(self, current = None):
          self._annotationLinksLoaded = False
          self._annotationLinksSeq = None;

      def _getAnnotationLinks(self, current = None):
          self.errorIfUnloaded()
          return self._annotationLinksSeq

      def _setAnnotationLinks(self, _annotationLinks, current = None):
          self.errorIfUnloaded()
          self._annotationLinksSeq = _annotationLinks
          self.checkUnloadedProperty(_annotationLinks,'annotationLinksLoaded')

      def isAnnotationLinksLoaded(self):
          return self._annotationLinksLoaded

      def sizeOfAnnotationLinks(self, current = None):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: return -1
          return len(self._annotationLinksSeq)

      def copyAnnotationLinks(self, current = None):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          return list(self._annotationLinksSeq)

      def iterateAnnotationLinks(self):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          return iter(self._annotationLinksSeq)

      def addPixelsAnnotationLink(self, target, current = None):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          self._annotationLinksSeq.append( target );
          target.setParent( self )

      def addAllPixelsAnnotationLinkSet(self, targets, current = None):
          self.errorIfUnloaded()
          if  not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          self._annotationLinksSeq.extend( targets )
          for target in targets:
              target.setParent( self )

      def removePixelsAnnotationLink(self, target, current = None):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          self._annotationLinksSeq.remove( target )
          target.setParent( None )

      def removeAllPixelsAnnotationLinkSet(self, targets, current = None):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          for elt in targets:
              elt.setParent( None )
              self._annotationLinksSeq.remove( elt )

      def clearAnnotationLinks(self, current = None):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          for elt in self._annotationLinksSeq:
              elt.setParent( None )
          self._annotationLinksSeq = list()

      def reloadAnnotationLinks(self, toCopy, current = None):
          self.errorIfUnloaded()
          if self._annotationLinksLoaded:
              raise omero.ClientError("Cannot reload active collection: annotationLinksSeq")
          if not toCopy:
              raise omero.ClientError("Argument cannot be null")
          if toCopy.getId().getValue() != self.getId().getValue():
             raise omero.ClientError("Argument must have the same id as this instance")
          if toCopy.getDetails().getUpdateEvent().getId().getValue() < self.getDetails().getUpdateEvent().getId().getValue():
             raise omero.ClientError("Argument may not be older than this instance")
          copy = toCopy.copyAnnotationLinks() # May also throw
          for elt in copy:
              elt.setParent( self )
          self._annotationLinksSeq = copy
          toCopy.unloadAnnotationLinks()
          self._annotationLinksLoaded = True

      def getAnnotationLinksCountPerOwner(self, current = None):
          return self._annotationLinksCountPerOwner

      def linkAnnotation(self, addition, current = None):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          link = _omero_model.PixelsAnnotationLinkI()
          link.link( self, addition );
          self.addPixelsAnnotationLinkToBoth( link, True )
          return link

      def addPixelsAnnotationLinkToBoth(self, link, bothSides):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          self._annotationLinksSeq.append( link )

      def findPixelsAnnotationLink(self, removal, current = None):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          result = list()
          for link in self._annotationLinksSeq:
              if link.getChild() == removal: result.append(link)
          return result

      def unlinkAnnotation(self, removal, current = None):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          toRemove = self.findPixelsAnnotationLink(removal)
          for next in toRemove:
              self.removePixelsAnnotationLinkFromBoth( next, True )

      def removePixelsAnnotationLinkFromBoth(self, link, bothSides, current = None):
          self.errorIfUnloaded()
          if not self._annotationLinksLoaded: self.throwNullCollectionException("annotationLinksSeq")
          self._annotationLinksSeq.remove( link )

      def linkedAnnotationList(self, current = None):
          self.errorIfUnloaded()
          if not self.annotationLinksLoaded: self.throwNullCollectionException("AnnotationLinks")
          linked = []
          for link in self._annotationLinksSeq:
              linked.append( link.getChild() )
          return linked


      def ice_postUnmarshal(self):
          """
          Provides additional initialization once all data loaded
          """
          pass # Currently unused


      def ice_preMarshal(self):
          """
          Provides additional validation before data is sent
          """
          pass # Currently unused

      def __getattr__(self, name):
          import __builtin__
          """
          Reroutes all access to object.field through object.getField() or object.isField()
          """
          field  = "_" + name
          capitalized = name[0].capitalize() + name[1:]
          getter = "get" + capitalized
          questn = "is" + capitalized
          try:
              self.__dict__[field]
              if hasattr(self, getter):
                  method = getattr(self, getter)
                  return method()
              elif hasattr(self, questn):
                  method = getattr(self, questn)
                  return method()
          except:
              pass
          raise AttributeError("'%s' object has no attribute '%s' or '%s'" % (self.__class__.__name__, getter, questn))

      def __setattr__(self, name, value):
          """
          Reroutes all access to object.field through object.getField(), with the caveat
          that all sets on variables starting with "_" are permitted directly.
          """
          if name.startswith("_"):
              self.__dict__[name] = value
              return
          else:
              field  = "_" + name
              setter = "set" + name[0].capitalize() + name[1:]
              if hasattr(self, field) and hasattr(self, setter):
                  method = getattr(self, setter)
                  return method(value)
          raise AttributeError("'%s' object has no attribute '%s'" % (self.__class__.__name__, setter))

_omero_model.PixelsI = PixelsI
