# **********************************************************************
#
# Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.5.1
#
# <auto-generated>
#
# Generated from file `IRepositoryInfo.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy
import omero_ModelF_ice
import omero_ServicesF_ice
import omero_System_ice
import omero_Collections_ice

# Included module omero
_M_omero = Ice.openModule('omero')

# Included module omero.model
_M_omero.model = Ice.openModule('omero.model')

# Included module Ice
_M_Ice = Ice.openModule('Ice')

# Included module Glacier2
_M_Glacier2 = Ice.openModule('Glacier2')

# Included module omero.sys
_M_omero.sys = Ice.openModule('omero.sys')

# Included module omero.api
_M_omero.api = Ice.openModule('omero.api')

# Included module omero.grid
_M_omero.grid = Ice.openModule('omero.grid')

# Start of module omero
__name__ = 'omero'

# Start of module omero.api
__name__ = 'omero.api'

if 'IRepositoryInfo' not in _M_omero.api.__dict__:
    _M_omero.api.IRepositoryInfo = Ice.createTempClass()
    class IRepositoryInfo(_M_omero.api.ServiceInterface):
        '''See IRepositoryInfo.html'''
        def __init__(self):
            if Ice.getType(self) == _M_omero.api.IRepositoryInfo:
                raise RuntimeError('omero.api.IRepositoryInfo is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::omero::api::IRepositoryInfo', '::omero::api::ServiceInterface')

        def ice_id(self, current=None):
            return '::omero::api::IRepositoryInfo'

        def ice_staticId():
            return '::omero::api::IRepositoryInfo'
        ice_staticId = staticmethod(ice_staticId)

        def getUsedSpaceInKilobytes_async(self, _cb, current=None):
            pass

        def getFreeSpaceInKilobytes_async(self, _cb, current=None):
            pass

        def getUsageFraction_async(self, _cb, current=None):
            pass

        def sanityCheckRepository_async(self, _cb, current=None):
            pass

        def removeUnusedFiles_async(self, _cb, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_omero.api._t_IRepositoryInfo)

        __repr__ = __str__

    _M_omero.api.IRepositoryInfoPrx = Ice.createTempClass()
    class IRepositoryInfoPrx(_M_omero.api.ServiceInterfacePrx):

        def getUsedSpaceInKilobytes(self, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_getUsedSpaceInKilobytes.invoke(self, ((), _ctx))

        def begin_getUsedSpaceInKilobytes(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_getUsedSpaceInKilobytes.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getUsedSpaceInKilobytes(self, _r):
            return _M_omero.api.IRepositoryInfo._op_getUsedSpaceInKilobytes.end(self, _r)

        def getUsedSpaceInKilobytes_async(self, _cb, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_getUsedSpaceInKilobytes.invokeAsync(self, (_cb, (), _ctx))

        def getFreeSpaceInKilobytes(self, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_getFreeSpaceInKilobytes.invoke(self, ((), _ctx))

        def begin_getFreeSpaceInKilobytes(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_getFreeSpaceInKilobytes.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getFreeSpaceInKilobytes(self, _r):
            return _M_omero.api.IRepositoryInfo._op_getFreeSpaceInKilobytes.end(self, _r)

        def getFreeSpaceInKilobytes_async(self, _cb, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_getFreeSpaceInKilobytes.invokeAsync(self, (_cb, (), _ctx))

        def getUsageFraction(self, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_getUsageFraction.invoke(self, ((), _ctx))

        def begin_getUsageFraction(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_getUsageFraction.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getUsageFraction(self, _r):
            return _M_omero.api.IRepositoryInfo._op_getUsageFraction.end(self, _r)

        def getUsageFraction_async(self, _cb, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_getUsageFraction.invokeAsync(self, (_cb, (), _ctx))

        def sanityCheckRepository(self, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_sanityCheckRepository.invoke(self, ((), _ctx))

        def begin_sanityCheckRepository(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_sanityCheckRepository.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_sanityCheckRepository(self, _r):
            return _M_omero.api.IRepositoryInfo._op_sanityCheckRepository.end(self, _r)

        def sanityCheckRepository_async(self, _cb, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_sanityCheckRepository.invokeAsync(self, (_cb, (), _ctx))

        def removeUnusedFiles(self, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_removeUnusedFiles.invoke(self, ((), _ctx))

        def begin_removeUnusedFiles(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_removeUnusedFiles.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_removeUnusedFiles(self, _r):
            return _M_omero.api.IRepositoryInfo._op_removeUnusedFiles.end(self, _r)

        def removeUnusedFiles_async(self, _cb, _ctx=None):
            return _M_omero.api.IRepositoryInfo._op_removeUnusedFiles.invokeAsync(self, (_cb, (), _ctx))

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_omero.api.IRepositoryInfoPrx.ice_checkedCast(proxy, '::omero::api::IRepositoryInfo', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_omero.api.IRepositoryInfoPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_omero.api._t_IRepositoryInfoPrx = IcePy.defineProxy('::omero::api::IRepositoryInfo', IRepositoryInfoPrx)

    _M_omero.api._t_IRepositoryInfo = IcePy.defineClass('::omero::api::IRepositoryInfo', IRepositoryInfo, -1, (), True, False, None, (_M_omero.api._t_ServiceInterface,), ())
    IRepositoryInfo._ice_type = _M_omero.api._t_IRepositoryInfo

    IRepositoryInfo._op_getUsedSpaceInKilobytes = IcePy.Operation('getUsedSpaceInKilobytes', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, True, None, (), (), (), ((), IcePy._t_long, False, 0), (_M_omero._t_ServerError,))
    IRepositoryInfo._op_getFreeSpaceInKilobytes = IcePy.Operation('getFreeSpaceInKilobytes', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, True, None, (), (), (), ((), IcePy._t_long, False, 0), (_M_omero._t_ServerError,))
    IRepositoryInfo._op_getUsageFraction = IcePy.Operation('getUsageFraction', Ice.OperationMode.Idempotent, Ice.OperationMode.Idempotent, True, None, (), (), (), ((), IcePy._t_double, False, 0), (_M_omero._t_ServerError,))
    IRepositoryInfo._op_sanityCheckRepository = IcePy.Operation('sanityCheckRepository', Ice.OperationMode.Normal, Ice.OperationMode.Normal, True, None, (), (), (), None, (_M_omero._t_ServerError,))
    IRepositoryInfo._op_removeUnusedFiles = IcePy.Operation('removeUnusedFiles', Ice.OperationMode.Normal, Ice.OperationMode.Normal, True, None, (), (), (), None, (_M_omero._t_ServerError,))

    _M_omero.api.IRepositoryInfo = IRepositoryInfo
    del IRepositoryInfo

    _M_omero.api.IRepositoryInfoPrx = IRepositoryInfoPrx
    del IRepositoryInfoPrx

# End of module omero.api

__name__ = 'omero'

# End of module omero
