# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtk_viewer_select_mode.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_vtk_viewer_select_mode(object):
    def setupUi(self, vtk_viewer_select_mode):
        vtk_viewer_select_mode.setObjectName("vtk_viewer_select_mode")
        vtk_viewer_select_mode.resize(516, 103)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(vtk_viewer_select_mode.sizePolicy().hasHeightForWidth())
        vtk_viewer_select_mode.setSizePolicy(sizePolicy)
        vtk_viewer_select_mode.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        vtk_viewer_select_mode.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridLayout_2 = QtWidgets.QGridLayout(vtk_viewer_select_mode)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.polydata_label = QtWidgets.QLabel(vtk_viewer_select_mode)
        self.polydata_label.setMouseTracking(True)
        self.polydata_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.polydata_label.setObjectName("polydata_label")
        self.gridLayout.addWidget(self.polydata_label, 3, 2, 1, 1)
        self.image1_cb = QtWidgets.QComboBox(vtk_viewer_select_mode)
        self.image1_cb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.image1_cb.setObjectName("image1_cb")
        self.gridLayout.addWidget(self.image1_cb, 2, 3, 1, 1)
        self.image1_label = QtWidgets.QLabel(vtk_viewer_select_mode)
        self.image1_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.image1_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.image1_label.setObjectName("image1_label")
        self.gridLayout.addWidget(self.image1_label, 2, 2, 1, 1)
        self.polydata_cb = QtWidgets.QComboBox(vtk_viewer_select_mode)
        self.polydata_cb.setEnabled(True)
        self.polydata_cb.setFrame(True)
        self.polydata_cb.setObjectName("polydata_cb")
        self.gridLayout.addWidget(self.polydata_cb, 3, 3, 1, 1)
        self.image2_cb = QtWidgets.QComboBox(vtk_viewer_select_mode)
        self.image2_cb.setObjectName("image2_cb")
        self.gridLayout.addWidget(self.image2_cb, 1, 3, 1, 1)
        self.image2_label = QtWidgets.QLabel(vtk_viewer_select_mode)
        self.image2_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.image2_label.setObjectName("image2_label")
        self.gridLayout.addWidget(self.image2_label, 1, 2, 1, 1)
        self.slice_label = QtWidgets.QLabel(vtk_viewer_select_mode)
        self.slice_label.setAlignment(QtCore.Qt.AlignCenter)
        self.slice_label.setObjectName("slice_label")
        self.gridLayout.addWidget(self.slice_label, 3, 4, 1, 1)
        self.synchro_cb = QtWidgets.QCheckBox(vtk_viewer_select_mode)
        self.synchro_cb.setObjectName("synchro_cb")
        self.gridLayout.addWidget(self.synchro_cb, 1, 4, 1, 2)
        self.axis_label = QtWidgets.QLabel(vtk_viewer_select_mode)
        self.axis_label.setAlignment(QtCore.Qt.AlignCenter)
        self.axis_label.setObjectName("axis_label")
        self.gridLayout.addWidget(self.axis_label, 1, 6, 1, 1)
        self.axis_cb = QtWidgets.QComboBox(vtk_viewer_select_mode)
        self.axis_cb.setObjectName("axis_cb")
        self.axis_cb.addItem("")
        self.axis_cb.addItem("")
        self.axis_cb.addItem("")
        self.gridLayout.addWidget(self.axis_cb, 1, 7, 1, 1)
        self.slice_slider = QtWidgets.QSlider(vtk_viewer_select_mode)
        self.slice_slider.setMinimum(1)
        self.slice_slider.setMaximum(20)
        self.slice_slider.setProperty("value", 5)
        self.slice_slider.setOrientation(QtCore.Qt.Horizontal)
        self.slice_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slice_slider.setTickInterval(1)
        self.slice_slider.setObjectName("slice_slider")
        self.gridLayout.addWidget(self.slice_slider, 3, 5, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 3, 1)
        self.cb_interactor_choice = QtWidgets.QComboBox(vtk_viewer_select_mode)
        self.cb_interactor_choice.setObjectName("cb_interactor_choice")
        self.gridLayout_2.addWidget(self.cb_interactor_choice, 0, 0, 1, 1)
        self.action_launch_button = QtWidgets.QPushButton(vtk_viewer_select_mode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action_launch_button.sizePolicy().hasHeightForWidth())
        self.action_launch_button.setSizePolicy(sizePolicy)
        self.action_launch_button.setMinimumSize(QtCore.QSize(0, 0))
        self.action_launch_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.action_launch_button.setBaseSize(QtCore.QSize(0, 0))
        self.action_launch_button.setIconSize(QtCore.QSize(16, 10))
        self.action_launch_button.setObjectName("action_launch_button")
        self.gridLayout_2.addWidget(self.action_launch_button, 2, 0, 1, 1)

        self.retranslateUi(vtk_viewer_select_mode)
        self.axis_cb.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(vtk_viewer_select_mode)

    def retranslateUi(self, vtk_viewer_select_mode):
        _translate = QtCore.QCoreApplication.translate
        vtk_viewer_select_mode.setWindowTitle(_translate("vtk_viewer_select_mode", "Form"))
        self.polydata_label.setToolTip(_translate("vtk_viewer_select_mode", "choose your points"))
        self.polydata_label.setText(_translate("vtk_viewer_select_mode", "TextLabel"))
        self.image1_label.setToolTip(_translate("vtk_viewer_select_mode", "choose your segmented matrix"))
        self.image1_label.setText(_translate("vtk_viewer_select_mode", "<html><head/><body><p>Segmented</p></body></html>"))
        self.image2_label.setToolTip(_translate("vtk_viewer_select_mode", "choose your intensity matrix"))
        self.image2_label.setText(_translate("vtk_viewer_select_mode", "<html><head/><body><p>Intensity</p></body></html>"))
        self.slice_label.setText(_translate("vtk_viewer_select_mode", "Width"))
        self.synchro_cb.setText(_translate("vtk_viewer_select_mode", "Synchronize"))
        self.axis_label.setText(_translate("vtk_viewer_select_mode", "Axis"))
        self.axis_cb.setItemText(0, _translate("vtk_viewer_select_mode", "X"))
        self.axis_cb.setItemText(1, _translate("vtk_viewer_select_mode", "Y"))
        self.axis_cb.setItemText(2, _translate("vtk_viewer_select_mode", "Z"))
        self.cb_interactor_choice.setToolTip(_translate("vtk_viewer_select_mode", "choose your interaction mode"))
        self.action_launch_button.setToolTip(_translate("vtk_viewer_select_mode", "Start the selected cell edition"))
        self.action_launch_button.setText(_translate("vtk_viewer_select_mode", "Edit Cell"))

